#define DLINKED 1
#define SORTALGO_EQ_NOSORT 0
#define SORTALGO_EQ_INSERTIONSORT 1
#define SORTALGO_EQ_BUBBLESORT 0

#if SORTALGO_EQ_BUBBLESORT || SORTALGO_EQ_INSERTIONSORT
#define SORTORDER_EQ_UPWARD 0
#define SORTORDER_EQ_DOWNWARD 1
#endif
