rename 's/\.jad/.java/' ./refactoring/CompleteFunctionRefactoring.jad
rename 's/\.jad/.java/' ./refactoring/RefactoringConfigurationException.jad
rename 's/\.jad/.java/' ./refactoring/actions/CompleteFunctionRefactoring.jad
rename 's/\.jad/.java/' ./refactoring/actions/ClassIntroductionRefactoring.jad
rename 's/\.jad/.java/' ./refactoring/actions/HookRefactoring.jad
rename 's/\.jad/.java/' ./refactoring/actions/DirectivesRefactoring.jad
rename 's/\.jad/.java/' ./refactoring/RefactoringRule.jad
rename 's/\.jad/.java/' ./refactoring/RefactoringDocument.jad
rename 's/\.jad/.java/' ./refactoring/RefactoringAction.jad
rename 's/\.jad/.java/' ./refactoring/RefactoringFactory.jad
rename 's/\.jad/.java/' ./refactoring/RefactoringStrategy.jad
rename 's/\.jad/.java/' ./refactoring/RefactoringConfiguration.jad
rename 's/\.jad/.java/' ./scanner/NameSpaceConfigs.jad
rename 's/\.jad/.java/' ./scanner/PreprocessorTree.jad
rename 's/\.jad/.java/' ./scanner/FeatureSearcher.jad
rename 's/\.jad/.java/' ./scanner/PreprocessorTree$NodeHolder.jad
rename 's/\.jad/.java/' ./scanner/FeaturePattern.jad
rename 's/\.jad/.java/' ./scanner/CheckLogics.jad
rename 's/\.jad/.java/' ./scanner/ReplaceFileException.jad
rename 's/\.jad/.java/' ./scanner/RemainingOccurrencesPattern.jad
rename 's/\.jad/.java/' ./scanner/patterns/InFunctionOccurrencesPattern.jad
rename 's/\.jad/.java/' ./scanner/patterns/CompleteFunctionPattern.jad
rename 's/\.jad/.java/' ./scanner/patterns/CompletePrivatePublicBlock.jad
rename 's/\.jad/.java/' ./scanner/patterns/ClassIntroductionPattern.jad
rename 's/\.jad/.java/' ./scanner/patterns/SwitchCasePattern.jad
rename 's/\.jad/.java/' ./scanner/patterns/DirectivesPattern.jad
rename 's/\.jad/.java/' ./analyzer/FeatureRefactoringAnalyzer$1.jad
rename 's/\.jad/.java/' ./analyzer/AnalyzeFeature.jad
rename 's/\.jad/.java/' ./analyzer/QueryBuilder.jad
rename 's/\.jad/.java/' ./analyzer/AnalyzedFeature.jad
rename 's/\.jad/.java/' ./analyzer/CriticalOccurrence.jad
rename 's/\.jad/.java/' ./analyzer/visitors/FeatureVisitor.jad
rename 's/\.jad/.java/' ./analyzer/FeatureRefactoringAnalyzer.jad
rename 's/\.jad/.java/' ./analyzer/FeatureRefactoringAnalyzer$2.jad
rename 's/\.jad/.java/' ./analyzer/SimpleHookCloneFinder.jad
rename 's/\.jad/.java/' ./org/eclipse/jdt/internal/jarinjarloader/RsrcURLConnection.jad
rename 's/\.jad/.java/' ./org/eclipse/jdt/internal/jarinjarloader/JarRsrcLoader.jad
rename 's/\.jad/.java/' ./org/eclipse/jdt/internal/jarinjarloader/RsrcURLStreamHandlerFactory.jad
rename 's/\.jad/.java/' ./org/eclipse/jdt/internal/jarinjarloader/JarRsrcLoader$ManifestInfo.jad
rename 's/\.jad/.java/' ./org/eclipse/jdt/internal/jarinjarloader/RsrcURLStreamHandler.jad
rename 's/\.jad/.java/' ./backend/PreprocessorNode.jad
rename 's/\.jad/.java/' ./backend/storage/IdentifiedFeature.jad
rename 's/\.jad/.java/' ./backend/storage/IdentifiedFeatureList.jad
rename 's/\.jad/.java/' ./backend/storage/PreprocessorOccurrence.jad
rename 's/\.jad/.java/' ./common/NodeTools$1.jad
rename 's/\.jad/.java/' ./common/xmlTemplates/FunctionBuilder.jad
rename 's/\.jad/.java/' ./common/xmlTemplates/NewFileTemplate.jad
